INSERT OR REPLACE INTO GameOptions
		(Type,												Description,											Help)
VALUES	('GAMEOPTION_JFD_AIOBSERVER_SUPPRESS_NOTIFS',	'TXT_KEY_GAMEOPTION_JFD_AIOBSERVER_SUPPRESS_NOTIFS',	'TXT_KEY_GAMEOPTION_JFD_AIOBSERVER_SUPPRESS_NOTIFS_HELP'),
		('GAMEOPTION_JFD_AIOBSERVER_SUPPRESS_POPUPS',	'TXT_KEY_GAMEOPTION_JFD_AIOBSERVER_SUPPRESS_POPUPS',	'TXT_KEY_GAMEOPTION_JFD_AIOBSERVER_SUPPRESS_POPUPS_HELP');
