INSERT OR REPLACE INTO IconFontTextures
		(IconFontTexture,						IconFontTextureFile)
VALUES	('ICON_FONT_TEXTURE_JFD_AIOBSERVER',	'JFDFontIcons_AIObserver_22');

INSERT OR REPLACE INTO IconFontMapping
		(IconName,				IconFontTexture,						IconMapping)
VALUES	('ICON_CITY',			'ICON_FONT_TEXTURE_JFD_AIOBSERVER',	23),
		('ICON_GOLD_NEG',		'ICON_FONT_TEXTURE_JFD_AIOBSERVER',	2),
		('ICON_GOLD_POS',		'ICON_FONT_TEXTURE_JFD_AIOBSERVER',	1),
		('ICON_GOLD_NEU',		'ICON_FONT_TEXTURE_JFD_AIOBSERVER',	4),
		('ICON_GOLD_EMP',		'ICON_FONT_TEXTURE_JFD_AIOBSERVER',	3),
		('ICON_IDEOLOGY_A',		'ICON_FONT_TEXTURE_JFD_AIOBSERVER',	13),
		('ICON_PANTHEON_A',		'ICON_FONT_TEXTURE_JFD_AIOBSERVER',	24);
