--==========================================================================================================================
-- FONT ICONS
--==========================================================================================================================
----------------------------------------------------------------------------------------------------------------------------	
-- IconFontTextures
----------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO IconFontTextures 
		(IconFontTexture, 							IconFontTextureFile)
VALUES	('ICON_FONT_TEXTURE_JFD_AIOBSERVER',		'JFDFontIcons_AIObserver_22'),
		('ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',	'JFDFontIcons_AIObserver_SovGovs_22');	
--------------------------------------------------------------------------------------------------------------------------
-- IconFontMapping
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO IconFontMapping 
		(IconName, 										IconFontTexture,									IconMapping)
VALUES	('ICON_RELATION_AFRAID',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					33),
		('ICON_RELATION_DECEPTIVE',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					37),
		('ICON_RELATION_HOSTILE',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					31),
		('ICON_RELATION_GUARDED',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					34),
		('ICON_RELATION_FRIENDLY',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					32),
		('ICON_RELATION_NEUTRAL',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					35),
		('ICON_RELATION_UNMET',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					36),
		('ICON_RELATION_WAR',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					19),
		('ICON_CAPITAL_A',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					19),
		('ICON_CAPITAL_CAPTURED',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					20),
		('ICON_CITY',									'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					23),
		('ICON_CULTURE_A',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					11),
		('ICON_DOF',									'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					30),
		('ICON_DOF_NOT',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					41),
		('ICON_EMBASSY_NOT',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					42),
		('ICON_LEGEND_ERA_1', 							'ICON_FONT_TEXTURE_JFD_OVERLAYMAPS_PLAYERS',		31),
		('ICON_LEGEND_ERA_2', 							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					43),
		('ICON_LEGEND_ERA_3', 							'ICON_FONT_TEXTURE_JFD_OVERLAYMAPS_PLAYERS',		33),
		('ICON_LEGEND_ERA_4', 							'ICON_FONT_TEXTURE_JFD_OVERLAYMAPS_PLAYERS',		34),
		('ICON_LEGEND_ERA_5', 							'ICON_FONT_TEXTURE_JFD_OVERLAYMAPS_PLAYERS',		35),
		('ICON_LEGEND_ERA_6', 							'ICON_FONT_TEXTURE_JFD_OVERLAYMAPS_PLAYERS',		36),
		('ICON_LEGEND_ERA_7', 							'ICON_FONT_TEXTURE_JFD_OVERLAYMAPS_PLAYERS',		37),
		('ICON_LEGEND_ERA_8', 							'ICON_FONT_TEXTURE_JFD_OVERLAYMAPS_PLAYERS',		38),
		('ICON_LEGEND_ERA_9', 							'ICON_FONT_TEXTURE_JFD_OVERLAYMAPS_PLAYERS',		39),
		('ICON_LEGEND_ERA_10', 							'ICON_FONT_TEXTURE_JFD_OVERLAYMAPS_PLAYERS',		40),
		('ICON_FOOD_NEG',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					26),
		('ICON_FOOD_POS',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					25),
		('ICON_FOOD_NEU', 								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					27),
		('ICON_FOOD_VPOS',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					28),
		('ICON_GOLD_NEG',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					2),
		('ICON_GOLD_POS',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					1),
		('ICON_GOLD_NEU', 								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					4),
		('ICON_GOLD_EMP',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					3),
		('ICON_GOVERNMENT',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					7),
		('ICON_GOVERNMENT_A',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					8),
		('ICON_LEGISLATURE',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					9),
		('ICON_LEGISLATURE_A',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					10),
		('ICON_IDEOLOGY',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					14),
		('ICON_IDEOLOGY_A',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					13),
		('ICON_IDEOLOGY_OPINION_1',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					15),
		('ICON_IDEOLOGY_OPINION_2',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					16),
		('ICON_IDEOLOGY_OPINION_3',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					17),
		('ICON_IDEOLOGY_OPINION_4',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					18),
		('ICON_NORMAL_AGE',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					43),
		('ICON_OPEN_BORDERS_NOT',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					40),
		('ICON_PANTHEON_A',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					24),
		('ICON_PEACE_FORCED',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					29),
		('ICON_RELIGION_A',								'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					12),
		('ICON_RESEARCH_NOT',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					39),
		('ICON_SCIENCE_POS',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					5),
		('ICON_SCIENCE_EMP',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					6),
		('ICON_STRENGTH_NOT',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					38),
		('ICON_TROPHY_IRON',							'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					21),
		('ICON_TROPHY_GRAPHITE',						'ICON_FONT_TEXTURE_JFD_AIOBSERVER',					22),
		--SOV GOVS
		('ICON_GOVERNMENT_JFD_MONARCHY',				'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				1),
		('ICON_GOVERNMENT_JFD_PRINCIPALITY',			'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				3),
		('ICON_GOVERNMENT_JFD_REPUBLIC',				'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				12),
		('ICON_GOVERNMENT_JFD_IMPERIAL',				'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				22),
		('ICON_GOVERNMENT_JFD_MERCHANT',				'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				17),
		('ICON_GOVERNMENT_JFD_MILITARY',				'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				19),
		('ICON_GOVERNMENT_JFD_NOMADIC',					'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				21),
		('ICON_GOVERNMENT_JFD_MONASTIC',				'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				18),
		('ICON_GOVERNMENT_JFD_REVOLUTIONARY',			'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				19),
		('ICON_GOVERNMENT_JFD_THEOCRATIC',				'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				15),
		('ICON_GOVERNMENT_JFD_TOTALITARIAN',			'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				7),
		('ICON_GOVERNMENT_JFD_TRIBAL',					'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				11),
		('ICON_GOVERNMENT_JFD_TRIBE',					'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				4),
		('ICON_GOVERNMENT_JFD_CALIPHATE',				'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				14),
		('ICON_GOVERNMENT_JFD_HOLY_ROMAN',				'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				8),
		('ICON_GOVERNMENT_JFD_MANDATE',					'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				9),
		('ICON_GOVERNMENT_JFD_MAMLUKE',					'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				23),
		('ICON_GOVERNMENT_JFD_PAPACY',					'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				7),
		('ICON_GOVERNMENT_JFD_SHOGUNATE',				'ICON_FONT_TEXTURE_JFD_AIOBSERVER_SOV',				16);
--==========================================================================================================================
--==========================================================================================================================