--==========================================================================================================================
-- MINI MAP OVERLAYS
--==========================================================================================================================
----------------------------------------------------------------------------------------------------------------------------
-- JFD_MinimapOverlays
----------------------------------------------------------------------------------------------------------------------------		  
INSERT INTO JFD_MinimapOverlays
		(Type,								Description,						IsDefault)
VALUES	('JFD_MINIMAP_DEFAULT',				'TXT_KEY_JFD_MINIMAP_DEFAULT',		1);

INSERT INTO JFD_MinimapOverlays
		(Type,								Description,						IsCultureTypes)
VALUES	('JFD_MINIMAP_CULTURES',			'TXT_KEY_JFD_MINIMAP_CULTURES',		1);

INSERT INTO JFD_MinimapOverlays
		(Type,								Description,						IsEras)
VALUES	('JFD_MINIMAP_ERAS',				'TXT_KEY_JFD_MINIMAP_ERAS',			1);

INSERT INTO JFD_MinimapOverlays
		(Type,								Description,						IsFactions)
VALUES	('JFD_MINIMAP_FACTIONS',			'TXT_KEY_JFD_MINIMAP_FACTIONS',		1);

INSERT INTO JFD_MinimapOverlays
		(Type,								Description,						IsGovernments)
VALUES	('JFD_MINIMAP_GOVERNMENTS',			'TXT_KEY_JFD_MINIMAP_GOVERNMENTS',	1);

INSERT INTO JFD_MinimapOverlays
		(Type,								Description,						IsIdeologies)
VALUES	('JFD_MINIMAP_IDEOLOGIES',			'TXT_KEY_JFD_MINIMAP_IDEOLOGIES',	1);

INSERT INTO JFD_MinimapOverlays
		(Type,								Description,						IsRelations)
VALUES	('JFD_MINIMAP_RELATIONS',			'TXT_KEY_JFD_MINIMAP_RELATIONS',	1);

INSERT INTO JFD_MinimapOverlays
		(Type,								Description,						IsReligions)
VALUES	('JFD_MINIMAP_RELIGIONS',			'TXT_KEY_JFD_MINIMAP_RELIGIONS',	1);

INSERT INTO JFD_MinimapOverlays
		(Type,								Description,						IsStability)
VALUES	('JFD_MINIMAP_STABILITY',			'TXT_KEY_JFD_MINIMAP_STABILITY',	1);
----------------------------------------------------------------------------------------------------------------------------
-- JFD_MinimapOverlay_Legends
----------------------------------------------------------------------------------------------------------------------------		  
INSERT INTO JFD_MinimapOverlay_Legends
		(MinimapOverlayType,				LegendType,								Description,										IsPlayer)
VALUES	('JFD_MINIMAP_DEFAULT',				'JFD_MINIMAP_LEGEND_DEFAULT',			'TXT_KEY_JFD_MINIMAP_LEGEND_DEFAULT',				1);	  

INSERT INTO JFD_MinimapOverlay_Legends
		(MinimapOverlayType,				LegendType,								Description,										IsType,								FontIcon,									ColorType)
VALUES	('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_ABORIGINAL',		'TXT_KEY_CULTURE_JFD_ABORIGINAL_SHORT_DESC',		'CULTURE_JFD_ABORIGINAL',			'[ICON_CULTURE_JFD_ABORIGINAL]',			'COLOR_PLAYER_DARK_RED'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_AMAZONIAN',			'TXT_KEY_CULTURE_JFD_AMAZONIAN_SHORT_DESC',			'CULTURE_JFD_AMAZONIAN',			'[ICON_CULTURE_JFD_AMAZONIAN]',				'COLOR_PLAYER_DARK_GREEN'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_ANDEAN',			'TXT_KEY_CULTURE_JFD_ANDEAN_SHORT_DESC',			'CULTURE_JFD_ANDEAN',				'[ICON_CULTURE_JFD_ANDEAN]',				'COLOR_PLAYER_INCA_BACKGROUND'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_BANTU',				'TXT_KEY_CULTURE_JFD_BANTU_SHORT_DESC',				'CULTURE_JFD_BANTU',				'[ICON_CULTURE_JFD_BANTU]',					'COLOR_PLAYER_DARK_ORANGE'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_BHARATA',			'TXT_KEY_CULTURE_JFD_BHARATA_SHORT_DESC',			'CULTURE_JFD_BHARATA',				'[ICON_CULTURE_JFD_BHARATA]',				'COLOR_PLAYER_INDIA_BACKGROUND'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_CENTRAL',			'TXT_KEY_CULTURE_JFD_CENTRAL_SHORT_DESC',			'CULTURE_JFD_CENTRAL',				'[ICON_CULTURE_JFD_CENTRAL]',				'COLOR_PLAYER_GERMANY_BACKGROUND'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_CENTRAL_AFRICAN',	'TXT_KEY_CULTURE_JFD_CENTRAL_AFRICAN_SHORT_DESC',	'CULTURE_JFD_CENTRAL_AFRICAN',		'[ICON_CULTURE_JFD_CENTRAL_AFRICAN]',		'COLOR_PLAYER_GRAY'),	
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_CLASSICAL',			'TXT_KEY_CULTURE_JFD_CLASSICAL_SHORT_DESC',			'CULTURE_JFD_CLASSICAL',			'[ICON_CULTURE_JFD_CLASSICAL]',				'COLOR_PLAYER_GREECE_BACKGROUND'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_COLONIAL',			'TXT_KEY_CULTURE_JFD_COLONIAL_SHORT_DESC',			'CULTURE_JFD_COLONIAL',				'[ICON_CULTURE_JFD_COLONIAL]',				'COLOR_PLAYER_AMERICA_BACKGROUND'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_EASTERN',			'TXT_KEY_CULTURE_JFD_EASTERN_SHORT_DESC',			'CULTURE_JFD_EASTERN',				'[ICON_CULTURE_JFD_EASTERN]',				'COLOR_PLAYER_RUSSIA_BACKGROUND'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_EAST_AFRICAN',		'TXT_KEY_CULTURE_JFD_EAST_AFRICAN_SHORT_DESC',		'CULTURE_JFD_EAST_AFRICAN',			'[ICON_CULTURE_JFD_EAST_AFRICAN]',			'COLOR_PLAYER_ETHIOPIA_BACKGROUND'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_EAST_INDIES',		'TXT_KEY_CULTURE_JFD_EAST_INDIES_SHORT_DESC',		'CULTURE_JFD_EAST_INDIES',			'[ICON_CULTURE_JFD_EAST_INDIES]',			'COLOR_PLAYER_INDONESIA_BACKGROUND'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_FAR_EASTERN',		'TXT_KEY_CULTURE_JFD_FAR_EASTERN_SHORT_DESC',		'CULTURE_JFD_FAR_EASTERN',			'[ICON_CULTURE_JFD_FAR_EASTERN]',			'COLOR_PLAYER_CHINA_BACKGROUND'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_GREAT_PLAINS',		'TXT_KEY_CULTURE_JFD_GREAT_PLAINS_SHORT_DESC',		'CULTURE_JFD_GREAT_PLAINS',			'[ICON_CULTURE_JFD_GREAT_PLAINS]',			'COLOR_PLAYER_SHOSHONE_BACKGROUND'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_HIMALAYAN',			'TXT_KEY_CULTURE_JFD_HIMALAYAN_SHORT_DESC',			'CULTURE_JFD_HIMALAYAN',			'[ICON_CULTURE_JFD_HIMALAYAN]',				'COLOR_PLAYER_LIGHT_ORANGE'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_INDOCHINA',			'TXT_KEY_CULTURE_JFD_INDOCHINA_SHORT_DESC',			'CULTURE_JFD_INDOCHINA',			'[ICON_CULTURE_JFD_INDOCHINA]',				'COLOR_PLAYER_SIAM_BACKGROUND'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_LEVANTINE',			'TXT_KEY_CULTURE_JFD_LEVANTINE_SHORT_DESC',			'CULTURE_JFD_LEVANTINE',			'[ICON_CULTURE_JFD_LEVANTINE]',				'COLOR_PLAYER_MIDDLE_PURPLE'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_MESOAMERICAN',		'TXT_KEY_CULTURE_JFD_MESOAMERICAN_SHORT_DESC',		'CULTURE_JFD_MESOAMERICAN',			'[ICON_CULTURE_JFD_MESOAMERICAN]',			'COLOR_PLAYER_AZTEC_BACKGROUND'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_MESOPOTAMIC',		'TXT_KEY_CULTURE_JFD_MESOPOTAMIC_SHORT_DESC',		'CULTURE_JFD_MESOPOTAMIC',			'[ICON_CULTURE_JFD_MESOPOTAMIC]',			'COLOR_PLAYER_NEBUCHADNEZZAR_BACKGROUND'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_MID_EASTERN',		'TXT_KEY_CULTURE_JFD_MID_EASTERN_SHORT_DESC',		'CULTURE_JFD_MID_EASTERN',			'[ICON_CULTURE_JFD_MID_EASTERN]',			'COLOR_PLAYER_ARABIA_BACKGROUND'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_NORTHERN',			'TXT_KEY_CULTURE_JFD_NORTHERN_SHORT_DESC',			'CULTURE_JFD_NORTHERN',				'[ICON_CULTURE_JFD_NORTHERN]',				'COLOR_PLAYER_DENMARK_BACKGROUND'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_OCEANIC',			'TXT_KEY_CULTURE_JFD_OCEANIC_SHORT_DESC',			'CULTURE_JFD_OCEANIC',				'[ICON_CULTURE_JFD_OCEANIC]',				'COLOR_PLAYER_POLYNESIA_BACKGROUND'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_PACIFIC',			'TXT_KEY_CULTURE_JFD_PACIFIC_SHORT_DESC',			'CULTURE_JFD_PACIFIC',				'[ICON_CULTURE_JFD_PACIFIC]',				'COLOR_PLAYER_LIGHT_BLUE'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_POLAR',				'TXT_KEY_CULTURE_JFD_POLAR_SHORT_DESC',				'CULTURE_JFD_POLAR',				'[ICON_CULTURE_JFD_POLAR]',					'COLOR_PLAYER_WHITE'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_SOUTHERN',			'TXT_KEY_CULTURE_JFD_SOUTHERN_SHORT_DESC',			'CULTURE_JFD_SOUTHERN',				'[ICON_CULTURE_JFD_SOUTHERN]',				'COLOR_PLAYER_VENICE_BACKGROUND'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_STEPPE',			'TXT_KEY_CULTURE_JFD_STEPPE_SHORT_DESC',			'CULTURE_JFD_STEPPE',				'[ICON_CULTURE_JFD_STEPPE]',				'COLOR_PLAYER_MONGOL_BACKGROUND'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_TOTALITARIAN',		'TXT_KEY_CULTURE_JFD_TOTALITARIAN_SHORT_DESC',		'CULTURE_JFD_TOTALITARIAN',			'[ICON_CULTURE_JFD_TOTALITARIAN]',			'COLOR_PLAYER_DARK_GRAY'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_WESTERN',			'TXT_KEY_CULTURE_JFD_WESTERN_SHORT_DESC',			'CULTURE_JFD_WESTERN',				'[ICON_CULTURE_JFD_WESTERN]',				'COLOR_PLAYER_ENGLAND_BACKGROUND'),			
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_WEST_AFRICAN',		'TXT_KEY_CULTURE_JFD_WEST_AFRICAN_SHORT_DESC',		'CULTURE_JFD_WEST_AFRICAN',			'[ICON_CULTURE_JFD_WEST_AFRICAN]',			'COLOR_PLAYER_SONGHAI_BACKGROUND'),		
		('JFD_MINIMAP_CULTURES',			'JFD_MINIMAP_LEGEND_WOODLANDS',			'TXT_KEY_CULTURE_JFD_WOODLANDS_SHORT_DESC',			'CULTURE_JFD_WOODLANDS',			'[ICON_CULTURE_JFD_WOODLANDS]',				'COLOR_PLAYER_IROQUOIS_BACKGROUND');		
		
UPDATE JFD_MinimapOverlay_Legends
SET IsTypeRequired = 1
WHERE MinimapOverlayType = 'JFD_MINIMAP_CULTURES';

INSERT INTO JFD_MinimapOverlay_Legends
		(MinimapOverlayType,				LegendType,								Description,										IsType,								FontIcon,									ColorType)									
VALUES	('JFD_MINIMAP_ERAS',				'JFD_MINIMAP_LEGEND_ERA_ANCIENT',		'TXT_KEY_LEGEND_JFD_ERA_ANCIENT',					'ERA_ANCIENT',						'[ICON_LEGEND_ERA_1]',						'COLOR_JFD_OVERLAY_ERA_ANCIENT'),			
		('JFD_MINIMAP_ERAS',				'JFD_MINIMAP_LEGEND_ERA_CLASSICAL',		'TXT_KEY_LEGEND_JFD_ERA_CLASSICAL',					'ERA_CLASSICAL',					'[ICON_LEGEND_ERA_2]',						'COLOR_JFD_OVERLAY_ERA_CLASSICAL'),			
		('JFD_MINIMAP_ERAS',				'JFD_MINIMAP_LEGEND_ERA_MEDIEVAL',		'TXT_KEY_LEGEND_JFD_ERA_MEDIEVAL',					'ERA_MEDIEVAL',						'[ICON_LEGEND_ERA_3]',						'COLOR_JFD_OVERLAY_ERA_MEDIEVAL'),					
		('JFD_MINIMAP_ERAS',				'JFD_MINIMAP_LEGEND_ERA_RENAISSANCE',	'TXT_KEY_LEGEND_JFD_ERA_RENAISSANCE',				'ERA_RENAISSANCE',					'[ICON_LEGEND_ERA_4]',						'COLOR_JFD_OVERLAY_ERA_RENAISSANCE'),				
		('JFD_MINIMAP_ERAS',				'JFD_MINIMAP_LEGEND_ERA_ENLIGHTENMENT',	'TXT_KEY_LEGEND_JFD_ERA_ENLIGHTENMENT',				'ERA_ENLIGHTENMENT',				'[ICON_LEGEND_ERA_5]',						'COLOR_JFD_OVERLAY_ERA_ENLIGHTENMENT'),		
		('JFD_MINIMAP_ERAS',				'JFD_MINIMAP_LEGEND_ERA_INDUSTRIAL',	'TXT_KEY_LEGEND_JFD_ERA_INDUSTRIAL',				'ERA_INDUSTRIAL',					'[ICON_LEGEND_ERA_6]',						'COLOR_JFD_OVERLAY_ERA_INDUSTRIAL'),	 			
		('JFD_MINIMAP_ERAS',				'JFD_MINIMAP_LEGEND_ERA_MODERN',		'TXT_KEY_LEGEND_JFD_ERA_MODERN',					'ERA_MODERN',						'[ICON_LEGEND_ERA_7]',						'COLOR_JFD_OVERLAY_ERA_MODERN'),					
		('JFD_MINIMAP_ERAS',				'JFD_MINIMAP_LEGEND_ERA_POSTMODERN',	'TXT_KEY_LEGEND_JFD_ERA_POSTMODERN',				'ERA_POSTMODERN',					'[ICON_LEGEND_ERA_8]',						'COLOR_JFD_OVERLAY_ERA_POSTMODERN'),					
		('JFD_MINIMAP_ERAS',				'JFD_MINIMAP_LEGEND_ERA_FUTURE',		'TXT_KEY_LEGEND_JFD_ERA_FUTURE',					'ERA_FUTURE',						'[ICON_LEGEND_ERA_9]',						'COLOR_JFD_OVERLAY_ERA_FUTURE');			

UPDATE JFD_MinimapOverlay_Legends
SET IsTypeRequired = 1
WHERE MinimapOverlayType = 'JFD_MINIMAP_ERAS';

INSERT INTO JFD_MinimapOverlay_Legends
		(MinimapOverlayType,				LegendType,								Description,										IsType,								FontIcon,									ColorType)					
VALUES	('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_MONARCHY',			'TXT_KEY_GOVERNMENT_JFD_MONARCHY_DESC',				'GOVERNMENT_JFD_MONARCHY',			'[ICON_GOVERNMENT_JFD_MONARCHY]',			'COLOR_JFD_OVERLAY_RED'),		
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_PRINCIPALITY',		'TXT_KEY_GOVERNMENT_JFD_PRINCIPALITY_DESC',			'GOVERNMENT_JFD_PRINCIPALITY',		'[ICON_GOVERNMENT_JFD_PRINCIPALITY]',		'COLOR_JFD_OVERLAY_YELLOW'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_REPUBLIC',			'TXT_KEY_GOVERNMENT_JFD_REPUBLIC_DESC',				'GOVERNMENT_JFD_REPUBLIC',			'[ICON_GOVERNMENT_JFD_REPUBLIC]',			'COLOR_JFD_OVERLAY_BLUE'),	
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_IMPERIAL',			'TXT_KEY_GOVERNMENT_JFD_IMPERIAL_DESC',				'GOVERNMENT_JFD_IMPERIAL',			'[ICON_GOVERNMENT_JFD_IMPERIAL]',			'COLOR_JFD_OVERLAY_PURPLE_DARK'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_MERCHANT',			'TXT_KEY_GOVERNMENT_JFD_MERCHANT_DESC',				'GOVERNMENT_JFD_MERCHANT',			'[ICON_GOVERNMENT_JFD_MERCHANT]',			'COLOR_JFD_OVERLAY_YELLOW_MIDDLE'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_MILITARY',			'TXT_KEY_GOVERNMENT_JFD_MILITARY_DESC',				'GOVERNMENT_JFD_MILITARY',			'[ICON_GOVERNMENT_JFD_MILITARY]',			'COLOR_JFD_OVERLAY_GREY_DARK'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_NOMADIC',			'TXT_KEY_GOVERNMENT_JFD_NOMADIC_DESC',				'GOVERNMENT_JFD_NOMADIC',			'[ICON_GOVERNMENT_JFD_NOMADIC]',			'COLOR_JFD_OVERLAY_BROWN'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_MONASTIC',			'TXT_KEY_GOVERNMENT_JFD_MONASTIC_DESC',				'GOVERNMENT_JFD_MONASTIC',			'[ICON_GOVERNMENT_JFD_MONASTIC]',			'COLOR_JFD_OVERLAY_PURPLE_LIGHT'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_REVOLUTIONARY',		'TXT_KEY_GOVERNMENT_JFD_REVOLUTIONARY_DESC',		'GOVERNMENT_JFD_REVOLUTIONARY',		'[ICON_GOVERNMENT_JFD_REVOLUTIONARY]',		'COLOR_JFD_OVERLAY_ORANGE_DARK'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_THEOCRATIC',		'TXT_KEY_GOVERNMENT_JFD_THEOCRATIC_DESC',			'GOVERNMENT_JFD_THEOCRATIC',		'[ICON_GOVERNMENT_JFD_THEOCRATIC]',			'COLOR_JFD_OVERLAY_WHITE'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_TOTALITARIAN',		'TXT_KEY_GOVERNMENT_JFD_TOTALITARIAN_DESC',			'GOVERNMENT_JFD_TOTALITARIAN',		'[ICON_GOVERNMENT_JFD_TOTALITARIAN]',		'COLOR_JFD_OVERLAY_BLACK'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_TRIBAL',			'TXT_KEY_GOVERNMENT_JFD_TRIBAL_DESC',				'GOVERNMENT_JFD_TRIBAL',			'[ICON_GOVERNMENT_JFD_TRIBAL]',				'COLOR_JFD_OVERLAY_ORANGE'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_CALIPHATE',			'TXT_KEY_GOVERNMENT_JFD_CALIPHATE_DESC',			'GOVERNMENT_JFD_CALIPHATE',			'[ICON_GOVERNMENT_JFD_CALIPHATE]',			'COLOR_JFD_OVERLAY_GREEN_DARK'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_HOLY_ROMAN',		'TXT_KEY_GOVERNMENT_JFD_HOLY_ROMAN_DESC',			'GOVERNMENT_JFD_HOLY_ROMAN',		'[ICON_GOVERNMENT_JFD_HOLY_ROMAN]',			'COLOR_JFD_OVERLAY_PURPLE_MIDDLE'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_MANDATE',			'TXT_KEY_GOVERNMENT_JFD_MANDATE_DESC',				'GOVERNMENT_JFD_MANDATE',			'[ICON_GOVERNMENT_JFD_MANDATE]',			'COLOR_JFD_OVERLAY_YELLOW_LIGHT'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_MAMLUKE',			'TXT_KEY_GOVERNMENT_JFD_MAMLUKE_DESC',				'GOVERNMENT_JFD_MAMLUKE',			'[ICON_GOVERNMENT_JFD_MAMLUKE]',			'COLOR_JFD_OVERLAY_YELLOW_DARK'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_PAPACY',			'TXT_KEY_GOVERNMENT_JFD_PAPACY_DESC',				'GOVERNMENT_JFD_PAPACY',			'[ICON_GOVERNMENT_JFD_PAPACY]',				'COLOR_JFD_OVERLAY_MAGENTA_LIGHT'),	
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_SHOGUNATE',			'TXT_KEY_GOVERNMENT_JFD_SHOGUNATE_DESC',			'GOVERNMENT_JFD_SHOGUNATE',			'[ICON_GOVERNMENT_JFD_SHOGUNATE]',			'COLOR_JFD_OVERLAY_RED_DARK'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_CITY_STATE',		'TXT_KEY_GOVERNMENT_JFD_CITY_STATE_DESC',			'GOVERNMENT_JFD_CITY_STATE',		'[ICON_CITY_STATE]',						'COLOR_JFD_OVERLAY_GREY'),
		('JFD_MINIMAP_GOVERNMENTS',			'JFD_MINIMAP_LEGEND_TRIBE',				'TXT_KEY_GOVERNMENT_JFD_TRIBE_DESC',				'GOVERNMENT_JFD_TRIBE',				'[ICON_GOVERNMENT_JFD_TRIBE]',				'COLOR_JFD_OVERLAY_BROWN_LIGHT');

UPDATE JFD_MinimapOverlay_Legends
SET IsTypeRequired = 1
WHERE MinimapOverlayType = 'JFD_MINIMAP_GOVERNMENTS' AND LegendType NOT IN ('JFD_MINIMAP_LEGEND_CITY_STATE');

INSERT INTO JFD_MinimapOverlay_Legends
		(MinimapOverlayType,				LegendType,								Description,											IsType,								FontIcon,									ColorType)								
VALUES	('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_COMMUNIST',			'TXT_KEY_JFD_FACTION_JFD_COMMUNIST_SHORT_DESC',			'FACTION_JFD_COMMUNIST',			'[ICON_JFD_FACTION_COMMUNIST]',				'COLOR_JFD_OVERLAY_RED_DARK'),					
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_CONSERVATIVE',		'TXT_KEY_JFD_FACTION_JFD_CONSERVATIVE_SHORT_DESC',		'FACTION_JFD_CONSERVATIVE',			'[ICON_JFD_FACTION_CONSERVATIVE]',			'COLOR_JFD_OVERLAY_BLUE'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_FASCIST',			'TXT_KEY_JFD_FACTION_JFD_FASCIST_SHORT_DESC',			'FACTION_JFD_FASCIST',				'[ICON_JFD_FACTION_FASCIST]',				'COLOR_JFD_OVERLAY_BLACK'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_GREEN',				'TXT_KEY_JFD_FACTION_JFD_GREEN_SHORT_DESC',				'FACTION_JFD_GREEN',				'[ICON_JFD_FACTION_GREEN]',					'COLOR_JFD_OVERLAY_GREEN'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_LIBERAL',			'TXT_KEY_JFD_FACTION_JFD_LIBERAL_SHORT_DESC',			'FACTION_JFD_LIBERAL',				'[ICON_JFD_FACTION_LIBERAL]',				'COLOR_JFD_OVERLAY_YELLOW'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_LIBERTARIAN',		'TXT_KEY_JFD_FACTION_JFD_LIBERTARIAN_SHORT_DESC',		'FACTION_JFD_LIBERTARIAN',			'[ICON_JFD_FACTION_LIBERTARIAN]',			'COLOR_JFD_OVERLAY_PURPLE'),					
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_INDEPENDENT',		'TXT_KEY_JFD_FACTION_JFD_INDEPENDENT_SHORT_DESC',		'FACTION_JFD_INDEPENDENT',			'[ICON_JFD_FACTION_INDEPENDENT]',			'COLOR_JFD_OVERLAY_YELLOW_MIDDLE'),			
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_NATIONAL',			'TXT_KEY_JFD_FACTION_JFD_NATIONAL_SHORT_DESC',			'FACTION_JFD_NATIONAL',				'[ICON_JFD_FACTION_NATIONAL]',				'COLOR_JFD_OVERLAY_RED_MIDDLE'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_NATIONALIST',		'TXT_KEY_JFD_FACTION_JFD_NATIONALIST_SHORT_DESC',		'FACTION_JFD_NATIONALIST',			'[ICON_JFD_FACTION_NATIONALIST]',			'COLOR_JFD_OVERLAY_BLACK'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_RELIGIOUS',			'TXT_KEY_JFD_FACTION_JFD_RELIGIOUS_SHORT_DESC',			'FACTION_JFD_RELIGIOUS',			'[ICON_JFD_FACTION_RELIGIOUS]',				'COLOR_JFD_OVERLAY_ORANGE'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_PROGRESSIVE',		'TXT_KEY_JFD_FACTION_JFD_PROGRESSIVE_SHORT_DESC',		'FACTION_JFD_PROGRESSIVE',			'[ICON_JFD_FACTION_PROGRESSIVE]',			'COLOR_JFD_OVERLAY_BLUE_LIGHT'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_RADICALIST',		'TXT_KEY_JFD_FACTION_JFD_RADICALIST_SHORT_DESC',		'FACTION_JFD_RADICALIST',			'[ICON_JFD_FACTION_RADICALIST]',			'COLOR_JFD_OVERLAY_ORANGE_DARK'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_SOCIALIST',			'TXT_KEY_JFD_FACTION_JFD_SOCIALIST_SHORT_DESC',			'FACTION_JFD_SOCIALIST',			'[ICON_JFD_FACTION_SOCIALIST]',				'COLOR_JFD_OVERLAY_RED'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_SOCIAL_DEMOCRATIC',	'TXT_KEY_JFD_FACTION_JFD_SOCIAL_DEMOCRATIC_SHORT_DESC',	'FACTION_JFD_SOCIAL_DEMOCRATIC',	'[ICON_JFD_FACTION_SOCIAL_DEMOCRATIC]',		'COLOR_JFD_OVERLAY_RED_LIGHT'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_THIRD_POSITIONIST',	'TXT_KEY_JFD_FACTION_JFD_THIRD_POSITIONIST_SHORT_DESC',	'FACTION_JFD_THIRD_POSITIONIST',	'[ICON_JFD_FACTION_THIRD_POSITIONIST]',		'COLOR_JFD_OVERLAY_GREY'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_ULTRANATIONALIST',	'TXT_KEY_JFD_FACTION_JFD_ULTRANATIONALIST_SHORT_DESC',	'FACTION_JFD_ULTRANATIONALIST',		'[ICON_JFD_FACTION_ULTRANATIONALIST]',		'COLOR_JFD_OVERLAY_BLUE_DARK'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_REVOLUTIONARIES',	'TXT_KEY_JFD_FACTION_JFD_REVOLUTIONARIES_SHORT_DESC',	'FACTION_JFD_REVOLUTIONARIES',		'[ICON_JFD_FACTION_REVOLUTIONARIES]',		'COLOR_JFD_OVERLAY_RED_DARK'),				
		('JFD_MINIMAP_FACTIONS',			'JFD_MINIMAP_LEGEND_TRADITIONAL',		'TXT_KEY_JFD_FACTION_JFD_TRADITIONAL_SHORT_DESC',		'FACTION_JFD_TRADITIONAL',			'[ICON_GOVERNMENT]',						'COLOR_JFD_OVERLAY_GREY');				

UPDATE JFD_MinimapOverlay_Legends
SET IsTypeRequired = 1
WHERE MinimapOverlayType = 'JFD_MINIMAP_FACTIONS' AND LegendType NOT IN ('JFD_MINIMAP_LEGEND_TRADITIONAL');

INSERT INTO JFD_MinimapOverlay_Legends	
		(MinimapOverlayType,				LegendType,								Description,										IsType,								FontIcon,									ColorType)				
VALUES	('JFD_MINIMAP_IDEOLOGIES',			'JFD_MINIMAP_LEGEND_AUTOCRACY',			'TXT_KEY_POLICY_BRANCH_AUTOCRACY',					'POLICY_BRANCH_AUTOCRACY',			'[ICON_IDEOLOGY_AUTOCRACY]',				'COLOR_JFD_OVERLAY_GREY_DARK'),			
		('JFD_MINIMAP_IDEOLOGIES',			'JFD_MINIMAP_LEGEND_FREEDOM',			'TXT_KEY_POLICY_BRANCH_FREEDOM',					'POLICY_BRANCH_FREEDOM',			'[ICON_IDEOLOGY_FREEDOM]',					'COLOR_JFD_OVERLAY_YELLOW'),		
		('JFD_MINIMAP_IDEOLOGIES',			'JFD_MINIMAP_LEGEND_NEUTRALITY',		'TXT_KEY_POLICY_BRANCH_JFD_NEUTRALITY',				'POLICY_BRANCH_JFD_NEUTRALITY',		'[ICON_IDEOLOGY_JFD_NEUTRALITY]',			'COLOR_JFD_OVERLAY_WHITE'),		
		('JFD_MINIMAP_IDEOLOGIES',			'JFD_MINIMAP_LEGEND_ORDER',				'TXT_KEY_POLICY_BRANCH_ORDER',						'POLICY_BRANCH_ORDER',				'[ICON_IDEOLOGY_ORDER]',					'COLOR_JFD_OVERLAY_RED'),				
		('JFD_MINIMAP_IDEOLOGIES',			'JFD_MINIMAP_LEGEND_SPIRIT',			'TXT_KEY_POLICY_BRANCH_JFD_SPIRIT',					'POLICY_BRANCH_JFD_SPIRIT',			'[ICON_IDEOLOGY_JFD_SPIRIT]',				'COLOR_JFD_OVERLAY_BLUE'),				
		('JFD_MINIMAP_IDEOLOGIES',			'JFD_MINIMAP_LEGEND_NONE',				'TXT_KEY_POLICY_BRANCH_JFD_NONE',					'POLICY_BRANCH_NONE',				'[ICON_LEGEND_NO_IDEOLOGY]',				'COLOR_JFD_OVERLAY_GREY');						

UPDATE JFD_MinimapOverlay_Legends
SET IsTypeRequired = 1
WHERE MinimapOverlayType = 'JFD_MINIMAP_IDEOLOGIES' AND LegendType != 'JFD_MINIMAP_LEGEND_NONE';

INSERT INTO JFD_MinimapOverlay_Legends	
		(MinimapOverlayType,				LegendType,								Description,										IsType,								FontIcon,									ColorType)				
VALUES	('JFD_MINIMAP_RELATIONS',			'JFD_MINIMAP_LEGEND_US',				'TXT_KEY_LEGEND_US',								'RELATION_US',						null,										null),			
		('JFD_MINIMAP_RELATIONS',			'JFD_MINIMAP_LEGEND_ALLIES',			'TXT_KEY_LEGEND_ALLIES',							'RELATION_ALLIES',					'[ICON_STRENGTH]',							'COLOR_JFD_OVERLAY_BLUE'),			
		('JFD_MINIMAP_RELATIONS',			'JFD_MINIMAP_LEGEND_FRIENDS',			'TXT_KEY_LEGEND_FRIENDS',							'RELATION_FRIENDS',					'[ICON_DOF]',								'COLOR_JFD_OVERLAY_GREEN'),		
		('JFD_MINIMAP_RELATIONS',			'JFD_MINIMAP_LEGEND_NEUTRAL',			'TXT_KEY_LEGEND_NEUTRAL',							'RELATION_NEUTRAL',					'[ICON_TEAM_1]',							'COLOR_JFD_OVERLAY_WHITE'),		
		('JFD_MINIMAP_RELATIONS',			'JFD_MINIMAP_LEGEND_ENEMIES',			'TXT_KEY_LEGEND_ENEMIES',							'RELATION_ENEMIES',					'[ICON_DENOUNCE]',							'COLOR_JFD_OVERLAY_ORANGE'),				
		('JFD_MINIMAP_RELATIONS',			'JFD_MINIMAP_LEGEND_WAR',				'TXT_KEY_LEGEND_WAR',								'RELATION_WAR',						'[ICON_WAR]',								'COLOR_JFD_OVERLAY_RED'),				
		('JFD_MINIMAP_RELATIONS',			'JFD_MINIMAP_LEGEND_UNMET',				'TXT_KEY_LEGEND_UNMET',								'RELATION_UNMET',					'[ICON_LOCKED]',							'COLOR_JFD_OVERLAY_GREY');						

UPDATE JFD_MinimapOverlay_Legends
SET UseFilterPlayerColor = 1, UseFilterPlayerIcon = 1
WHERE LegendType = 'JFD_MINIMAP_LEGEND_US';

INSERT INTO JFD_MinimapOverlay_Legends	
		(MinimapOverlayType,				LegendType,								Description,										IsType,								FontIcon,									ColorType)				
VALUES	('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_BUDDHISM',			'TXT_KEY_RELIGION_BUDDHISM',						'RELIGION_BUDDHISM',				'[ICON_RELIGION_BUDDHISM]',					'COLOR_PLAYER_ORANGE'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_CHRISTIANITY',		'TXT_KEY_RELIGION_CHRISTIANITY',					'RELIGION_CHRISTIANITY',			'[ICON_RELIGION_CHRISTIANITY]',				'COLOR_PLAYER_DARK_YELLOW'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_CONFUCIANISM',		'TXT_KEY_RELIGION_CONFUCIANISM',					'RELIGION_CONFUCIANISM',			'[ICON_RELIGION_CONFUCIANISM]',				'COLOR_PLAYER_LIGHT_YELLOW'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_HINDUISM',			'TXT_KEY_RELIGION_HINDUISM',						'RELIGION_HINDUISM',				'[ICON_RELIGION_HINDUISM]',					'COLOR_CYAN'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_ISLAM',				'TXT_KEY_RELIGION_ISLAM',							'RELIGION_ISLAM',					'[ICON_RELIGION_ISLAM]',					'COLOR_PLAYER_GREEN'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_ISLAM_IBADI',		'TXT_KEY_RELIGION_ISLAM_IBADI',						'RELIGION_ISLAM_IBADI',				'[ICON_RELIGION_ISLAM_IBADI]',				'COLOR_PLAYER_DARK_GREEN'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_ISLAM_SHIA',		'TXT_KEY_RELIGION_ISLAM_SHIA',						'RELIGION_ISLAM_SHIA',				'[ICON_RELIGION_ISLAM_SHIA]',				'COLOR_PLAYER_LIGHT_GREEN'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_JAIN',				'TXT_KEY_RELIGION_JAIN',							'RELIGION_JAIN',					'[ICON_RELIGION_JAIN]',						'COLOR_PLAYER_DARK_BLUE'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_JUDAISM',			'TXT_KEY_RELIGION_JUDAISM',							'RELIGION_JUDAISM',					'[ICON_RELIGION_JUDAISM]',					'COLOR_PLAYER_LIGHT_BLUE'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_ORTHODOXY',			'TXT_KEY_RELIGION_ORTHODOXY',						'RELIGION_ORTHODOXY',				'[ICON_RELIGION_ORTHODOX]Y',				'COLOR_PLAYER_PURPLE'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_MAHAYANA',			'TXT_KEY_RELIGION_MAHAYANA',						'RELIGION_MAHAYANA',				'[ICON_RELIGION_MAHAYANA]',					'COLOR_PLAYER_LIGHT_ORANGE'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_SHINTO',			'TXT_KEY_RELIGION_SHINTO',							'RELIGION_SHINTO',					'[ICON_RELIGION_SHINTO]',					'COLOR_PLAYER_RED'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_SIKHISM',			'TXT_KEY_RELIGION_SIKHISM',							'RELIGION_SIKHISM',					'[ICON_RELIGION_SIKHISM]',					'COLOR_PLAYER_DARK_CYAN'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_TAOISM',			'TXT_KEY_RELIGION_TAOISM',							'RELIGION_TAOISM',					'[ICON_RELIGION_TAOISM]',					'COLOR_PLAYER_DARK_LEMON'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_TENGRIISM',			'TXT_KEY_RELIGION_TENGRIISM',						'RELIGION_TENGRIISM',				'[ICON_RELIGION_TENGRIISM]',				'COLOR_PLAYER_DARK_RED'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_TLATEOMATILIZTLI',	'TXT_KEY_RELIGION_TLATEOMATILIZTLI',				'RELIGION_TLATEOMATILIZTLI',		'[ICON_RELIGION_TLATEOMATILIZTLI]',			'COLOR_PLAYER_MIDDLE_CYAN'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_VAJRAYANA',			'TXT_KEY_RELIGION_VAJRAYANA',						'RELIGION_VAJRAYANA',				'[ICON_RELIGION_VAJRAYANA]',				'COLOR_PLAYER_LIGHT_ORANGE'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_VODUN',				'TXT_KEY_RELIGION_VODUN',							'RELIGION_VODUN',					'[ICON_RELIGION_VODUN]',					'COLOR_PLAYER_LIGHT_PURPLE'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_ZOROASTRIANISM',	'TXT_KEY_RELIGION_ZOROASTRIANISM',					'RELIGION_ZOROASTRIANISM',			'[ICON_RELIGION_ZOROASTRIANISM]',			'COLOR_PLAYER_PALE_RED'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_PANTHEON',			'TXT_KEY_RELIGION_PANTHEON',						'RELIGION_PANTHEON',				'[ICON_RELIGION_PANTHEON]',					'COLOR_PLAYER_WHITE'),
		('JFD_MINIMAP_RELIGIONS',			'JFD_MINIMAP_LEGEND_NO_RELIGION',		'TXT_KEY_NO_RELIGION',								'NO_RELIGION',						'[ICON_PANTHEON_A]',						'COLOR_JFD_OVERLAY_GREY');

UPDATE JFD_MinimapOverlay_Legends
SET IsTypeRequired = 1
WHERE MinimapOverlayType = 'JFD_MINIMAP_RELIGIONS';

INSERT INTO JFD_MinimapOverlay_Legends	
		(MinimapOverlayType,				LegendType,								Description,										IsType,								FontIcon,									ColorType)				
VALUES	('JFD_MINIMAP_STABILITY',			'JFD_MINIMAP_LEGEND_GOLDEN_AGE',		'TXT_KEY_LEGEND_GOLDEN_AGE',						'STABILITY_GOLDEN_AGE',				'[ICON_GOLDEN_AGE]',						'COLOR_JFD_OVERLAY_GOLDEN_AGE'),			
		('JFD_MINIMAP_STABILITY',			'JFD_MINIMAP_LEGEND_DARK_AGE',			'TXT_KEY_LEGEND_DARK_AGE',							'STABILITY_DARK_AGE',				'[ICON_DARK_AGE]',							'COLOR_JFD_OVERLAY_DARK_AGE'),		
		('JFD_MINIMAP_STABILITY',			'JFD_MINIMAP_LEGEND_STABLE',			'TXT_KEY_LEGEND_STABLE',							'STABILITY_STABLE',					'[ICON_HAPPINESS_1]',						'COLOR_JFD_OVERLAY_HAPPINESS'),	
		('JFD_MINIMAP_STABILITY',			'JFD_MINIMAP_LEGEND_UNSTABLE',			'TXT_KEY_LEGEND_UNSTABLE',							'STABILITY_UNSTABLE',				'[ICON_HAPPINESS_3]',						'COLOR_JFD_OVERLAY_UNHAPPINESS_3'),		
		('JFD_MINIMAP_STABILITY',			'JFD_MINIMAP_LEGEND_V_UNSTABLE',		'TXT_KEY_LEGEND_V_UNSTABLE',						'STABILITY_V_UNSTABLE',				'[ICON_HAPPINESS_4]',						'COLOR_JFD_OVERLAY_UNHAPPINESS_4'),				
		('JFD_MINIMAP_STABILITY',			'JFD_MINIMAP_LEGEND_REBELLION',			'TXT_KEY_LEGEND_REBELLION',							'STABILITY_REBELLION',				'[ICON_TEAM_11]',							'COLOR_JFD_OVERLAY_BLACK'),				
		('JFD_MINIMAP_STABILITY',			'JFD_MINIMAP_LEGEND_ANARCHY',			'TXT_KEY_LEGEND_ANARCHY',							'STABILITY_ANARCHY',				'[ICON_RESISTANCE]',						'COLOR_JFD_OVERLAY_ANARCHY');						
--==========================================================================================================================			
--==========================================================================================================================